log_features = [
    'POSIX_OPENS_LOG10', 'POSIX_SEEKS_LOG10', 'POSIX_STATS_LOG10',
    'POSIX_MMAPS_LOG10', 'POSIX_FSYNCS_LOG10',
    'POSIX_MODE_LOG10', 'POSIX_MEM_ALIGNMENT_LOG10',
    'POSIX_FILE_ALIGNMENT_LOG10', 'NPROCS_LOG10',
    'POSIX_TOTAL_ACCESSES_LOG10', 'POSIX_TOTAL_BYTES_LOG10',
    'POSIX_TOTAL_FILES_LOG10',
    'NODES'
]
# 第一组百分比特征：记录文件访问模式和数据分布
perc_features1 = [
    'POSIX_BYTES_READ', 'POSIX_UNIQUE_BYTES', 'POSIX_SHARED_BYTES',
    'POSIX_READ_ONLY_BYTES', 'POSIX_READ_WRITE_BYTES', 'POSIX_WRITE_ONLY_BYTES',
    'POSIX_UNIQUE_FILES', 'POSIX_SHARED_FILES', 'POSIX_READ_ONLY_FILES',
    'POSIX_READ_WRITE_FILES', 'POSIX_WRITE_ONLY_FILES', 'POSIX_READS',
    'POSIX_WRITES', 'POSIX_RW_SWITCHES', 'POSIX_SEQ_READS', 'POSIX_SEQ_WRITES',
    'POSIX_CONSEC_READS', 'POSIX_CONSEC_WRITES', 'POSIX_FILE_NOT_ALIGNED',
    'POSIX_MEM_NOT_ALIGNED', 'POSIX_ACCESS1_COUNT', 'POSIX_ACCESS2_COUNT',
    'POSIX_ACCESS3_COUNT', 'POSIX_ACCESS4_COUNT'
]

# 第二组百分比特征：记录文件大小分布
perc_features2 = [
    'POSIX_SIZE_READ_0_100', 'POSIX_SIZE_READ_100_1K', 'POSIX_SIZE_READ_1K_10K',
    'POSIX_SIZE_READ_10K_100K', 'POSIX_SIZE_READ_100K_1M', 'POSIX_SIZE_READ_1M_4M',
    'POSIX_SIZE_READ_4M_10M', 'POSIX_SIZE_READ_10M_100M', 'POSIX_SIZE_READ_100M_1G',
    'POSIX_SIZE_READ_1G_PLUS', 'POSIX_SIZE_WRITE_0_100', 'POSIX_SIZE_WRITE_100_1K',
    'POSIX_SIZE_WRITE_1K_10K', 'POSIX_SIZE_WRITE_10K_100K', 'POSIX_SIZE_WRITE_100K_1M',
    'POSIX_SIZE_WRITE_1M_4M', 'POSIX_SIZE_WRITE_4M_10M', 'POSIX_SIZE_WRITE_10M_100M',
    'POSIX_SIZE_WRITE_100M_1G', 'POSIX_SIZE_WRITE_1G_PLUS'
]

# 百分比特征：将原始特征转换为百分比形式
perc_features = [
    'POSIX_BYTES_READ_PERC', 'POSIX_UNIQUE_BYTES_PERC', 'POSIX_SHARED_BYTES_PERC',
    'POSIX_READ_ONLY_BYTES_PERC', 'POSIX_READ_WRITE_BYTES_PERC',
    'POSIX_WRITE_ONLY_BYTES_PERC', 'POSIX_UNIQUE_FILES_PERC',
    'POSIX_SHARED_FILES_PERC', 'POSIX_READ_ONLY_FILES_PERC',
    'POSIX_READ_WRITE_FILES_PERC', 'POSIX_WRITE_ONLY_FILES_PERC',
    'POSIX_READS_PERC', 'POSIX_WRITES_PERC', 'POSIX_RW_SWITCHES_PERC',
    'POSIX_SEQ_READS_PERC', 'POSIX_SEQ_WRITES_PERC', 'POSIX_CONSEC_READS_PERC',
    'POSIX_CONSEC_WRITES_PERC', 'POSIX_FILE_NOT_ALIGNED_PERC',
    'POSIX_MEM_NOT_ALIGNED_PERC', 'POSIX_SIZE_READ_0_100_PERC',
    'POSIX_SIZE_READ_100_1K_PERC', 'POSIX_SIZE_READ_1K_10K_PERC',
    'POSIX_SIZE_READ_10K_100K_PERC', 'POSIX_SIZE_READ_100K_1M_PERC',
    'POSIX_SIZE_READ_1M_4M_PERC', 'POSIX_SIZE_READ_4M_10M_PERC',
    'POSIX_SIZE_READ_10M_100M_PERC', 'POSIX_SIZE_READ_100M_1G_PERC',
    'POSIX_SIZE_READ_1G_PLUS_PERC', 'POSIX_SIZE_WRITE_0_100_PERC',
    'POSIX_SIZE_WRITE_100_1K_PERC', 'POSIX_SIZE_WRITE_1K_10K_PERC',
    'POSIX_SIZE_WRITE_10K_100K_PERC', 'POSIX_SIZE_WRITE_100K_1M_PERC',
    'POSIX_SIZE_WRITE_1M_4M_PERC', 'POSIX_SIZE_WRITE_4M_10M_PERC',
    'POSIX_SIZE_WRITE_10M_100M_PERC', 'POSIX_SIZE_WRITE_100M_1G_PERC',
    'POSIX_SIZE_WRITE_1G_PLUS_PERC', 'POSIX_ACCESS1_COUNT_PERC',
    'POSIX_ACCESS2_COUNT_PERC', 'POSIX_ACCESS3_COUNT_PERC',
    'POSIX_ACCESS4_COUNT_PERC'
]
# 所有Darshan特征：合并基本日志特征和原始百分比特征
darshan_features = log_features + perc_features

# ROMIO特征：记录MPI-IO配置参数
romio_features = [
    'cb_read', 'cb_write', 'ds_read', 'ds_write', 'cb_nodes', 'cb_config_list'
]

# Lustre特征：记录Lustre文件系统特定参数
lustre_features = ['stripe_size', 'stripe_count']

# GekkoFS特征：记录GekkoFS文件系统特定参数
gkfs_features = [
    'gkfs_chunksize', 'gkfs_dirents_buff_size',
    'gkfs_daemon_io_xstreams', 'gkfs_daemon_handler_xstreams'
]
